### ISSUE TITLE
We should not force timestamps

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-changes#27]
Currently the monitored entries share the same `last_modified` value as the timestamp from list of records.

Is there any strong requirement for that (I know [there isn't in Firefox](https://dxr.mozilla.org/mozilla-central/rev/b1c31c4a0a678194931779e0f13fba7b508eb109/services/common/blocklist-updater.js#107-111)) ?

The [integrity constraint on the table](https://github.com/Kinto/kinto/blob/73a741ea8cc4a481bc1f5dccd9f706acb912ef14/kinto/core/storage/postgresql/schema.sql#L52-L53) is for the tuple (`parent_id`, `collection_id`, `timestamp`) so theorically two collections from different buckets can have the same timestamp! ...which will fail in this plugin. See https://github.com/Kinto/kinto-signer/issues/156

**Comment by Natim** [comment]
Yeah, let's remove that feature.
