### ISSUE TITLE
Add the changes capability

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-changes#6]

**Comment by leplatrem** [comment]
Maybe also add the names of bucket and collections were the changes are stored (public settings ?)

**Comment by Natim** [comment]
Isn't it already the case? You can even define the read permissions

**Comment by Natim** [comment]
Oh you mean in the capability! yes!

**Comment by vsham20** [comment]
This bug looks interesting to me, looking forward for some instructions to start with.

**Comment by Natim** [comment]
Sorry this bug was already fixed by @Sayli-Karnik here: https://github.com/Kinto/kinto-changes/pull/10
